[project]
name = "uncertainty"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "certifi>=2025.10.5",
    "datasets>=4.4.1",
    "einops>=0.8.1",
    "fancy-einsum>=0.0.3",
    "ipykernel>=7.1.0",
    "jaxtyping>=0.3.3",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "ruff>=0.14.4",
    "sae-lens>=6.21.0",
    "scipy>=1.16.3",
    "torch>=2.9.0",
    "transformer-lens>=2.16.1",
    "transformers>=4.57.1",
]
